// nc_http.cpp — fetch pipeline over a pluggable transport.
#include "nc_http.h"
#include "nc_config.h"
#include "nc_regex.h"

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <map>
#include <mutex>
#include <thread>

namespace nc {

namespace {

std::mutex g_mutex;
TransportFn g_transport;
std::map<std::string, std::string> g_extra_cookies; // domain -> cookie
std::string g_browser_command;
std::map<std::string, std::chrono::steady_clock::time_point> g_host_retry_after;

const char* kChallengePatterns[] = {
    "just a moment",       "cf_chl",           "cf-ray",
    "enable javascript and cookies",           "checking your browser",
    "<h1>403 forbidden</h1>",                  "<h1>403 error</h1>",
    "error: the request could not be satisfied", "generated by cloudfront",
    "please enable cookies", "datadome",
    /* AWS WAF (alphapolis etc.) */
    "awswaf", "awswafcookiedomainlist", "gokuprops",
    /* misc JS challenges / age gates */
    "challenge-error-text", "js-challenge", "captcha-delivery", "hcaptcha",
    "attention required", "\xe5\xb9\xb4\xe9\xbd\xa2\xe7\xa2\xba\xe8\xaa\x8d", /* 年齢確認 */
};

bool has_ascii_ci(const std::string& hay, const std::string& needle) {
    return contains_ci(hay, needle);
}

bool challenge_sample(const std::string& body, bool forbidden_variant) {
    std::string sample = body;
    if (sample.size() > 256 * 1024 + 16 * 1024) {
        sample = sample.substr(0, 256 * 1024) + sample.substr(sample.size() - 16 * 1024);
    }
    for (const char* p : kChallengePatterns)
        if (has_ascii_ci(sample, p)) return true;
    // Combo heuristics only apply to SMALL interstitial pages.  Real content
    // pages that merely reference Cloudflare/hcaptcha scripts must not match.
    if (sample.size() < 100 * 1024) {
        if (has_ascii_ci(sample, "cloudflare") &&
            (has_ascii_ci(sample, "cf_chl") || has_ascii_ci(sample, "cf-ray") ||
             has_ascii_ci(sample, "turnstile")))
            return true;
        if (forbidden_variant && has_ascii_ci(sample, "forbidden") &&
            has_ascii_ci(sample, "captcha"))
            return true;
    }
    return false;
}

std::string cookie_for_host(const std::string& host,
                            const std::optional<AccessSettings>& access) {
    std::vector<std::string> parts;
    {
        std::lock_guard<std::mutex> lock(g_mutex);
        for (auto& kv : g_extra_cookies) {
            const std::string& domain = kv.first;
            std::string d = domain;
            while (!d.empty() && d.front() == '.') d.erase(d.begin());
            while (!d.empty() && d.back() == '.') d.pop_back();
            if (host == d || ends_with(host, "." + d) ||
                (starts_with(host, "www.") && host.substr(4) == d) ||
                (starts_with(d, "www.") && d.substr(4) == host))
                parts.push_back(kv.second);
        }
    }
    if (access && access->cookies) parts.push_back(*access->cookies);
    return join(parts, "; ");
}

std::vector<std::pair<std::string, std::string>> browser_headers(
    const std::string& profile, const std::string& url,
    const std::optional<AccessSettings>& access,
    const std::optional<std::string>& referer_url) {
    std::vector<std::pair<std::string, std::string>> headers;
    headers.emplace_back(
        "Accept",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,"
        "image/apng,*/*;q=0.8");
    headers.emplace_back("Accept-Language", "ja-JP,ja;q=0.9,en-US;q=0.8,en;q=0.7");
    headers.emplace_back("Cache-Control", "max-age=0");
    headers.emplace_back("Pragma", "no-cache");
    headers.emplace_back("DNT", "1");
    headers.emplace_back("Upgrade-Insecure-Requests", "1");
    headers.emplace_back("User-Agent", profile_user_agent(profile));
    if (profile == "chrome_desktop") {
        headers.emplace_back(
            "sec-ch-ua",
            "\"Google Chrome\";v=\"147\", \"Chromium\";v=\"147\", \"Not.A/Brand\";v=\"24\"");
        headers.emplace_back("sec-ch-ua-mobile", "?0");
        headers.emplace_back("sec-ch-ua-platform", "\"macOS\"");
    }
    // sec-fetch-site must agree with the Referer added below; a "none" hint
    // together with a Referer header is a bot signal.
    std::string referer;
    if (access && access->referer) {
        if (*access->referer == "toc_parent") {
            if (referer_url) {
                UrlParts p;
                if (url_parse(*referer_url, p))
                    referer = p.scheme + "://" + p.host +
                              (p.port.empty() ? "" : ":" + p.port) + "/";
            }
        } else {
            referer = *access->referer;
        }
    }
    {
        std::string sfs = "none";
        if (!referer.empty()) {
            UrlParts rp, up;
            if (url_parse(referer, rp) && url_parse(url, up))
                sfs = lower(rp.host) == lower(up.host) ? "same-origin" : "cross-site";
            else
                sfs = "same-origin";
        }
        headers.emplace_back("sec-fetch-site", sfs);
        headers.emplace_back("sec-fetch-mode", "navigate");
        headers.emplace_back("sec-fetch-user", "?1");
        headers.emplace_back("sec-fetch-dest", "document");
    }
    if (access) {
        for (auto& kv : access->headers) {
            bool replaced = false;
            for (auto& existing : headers) {
                if (lower(existing.first) == lower(kv.first)) {
                    existing.second = kv.second;
                    replaced = true;
                }
            }
            if (!replaced) headers.push_back(kv);
        }
        if (!referer.empty()) headers.emplace_back("Referer", referer);
    }
    std::string cookie = cookie_for_host(url_host(url), access);
    if (!cookie.empty()) headers.emplace_back("Cookie", cookie);
    return headers;
}

std::string fetch_via_command(const std::string& command, const std::string& url) {
    std::string cmd = command + " " + "'" + replace_all(url, "'", "'\\''") + "'";
    FILE* pipe = popen(cmd.c_str(), "r");
    if (!pipe) throw Error("browser fetch command failed to start");
    std::string out;
    char buf[8192];
    while (true) {
        size_t n = std::fread(buf, 1, sizeof buf, pipe);
        if (n == 0) break;
        out.append(buf, n);
    }
    int rc = pclose(pipe);
    if (rc != 0 && out.empty()) throw Error("browser fetch command failed");
    return out;
}

// アクセス制限対策: ホストごとの最小リクエスト間隔(全リクエスト共通の土台)。
// エピソード逐次取得の RateLimiter に加え、目次ページ連打なども同一ホストに
// 対して最低間隔を空けて送る。NOVELDL_MIN_HOST_GAP_MS(既定 800ms、0 で無効)。
std::map<std::string, std::chrono::steady_clock::time_point> g_host_last_req;

int min_host_gap_ms() {
    const char* env = std::getenv("NOVELDL_MIN_HOST_GAP_MS");
    return env ? std::atoi(env) : 800;
}

void host_gap_wait(const std::string& host) {
    if (host.empty()) return;
    int gap = min_host_gap_ms();
    if (gap <= 0) return;
    std::chrono::steady_clock::time_point deadline;
    {
        std::lock_guard<std::mutex> lock(g_mutex);
        auto it = g_host_last_req.find(host);
        if (it != g_host_last_req.end())
            deadline = it->second + std::chrono::milliseconds(gap);
    }
    while (std::chrono::steady_clock::now() < deadline)
        std::this_thread::sleep_for(std::chrono::milliseconds(25));
    {
        std::lock_guard<std::mutex> lock(g_mutex);
        g_host_last_req[host] = std::chrono::steady_clock::now();
    }
}

HttpResponse transport_request(const std::string& url,
                               const std::vector<std::pair<std::string, std::string>>& headers,
                               int timeout) {
    host_gap_wait(url_host(url));
    TransportFn fn;
    {
        std::lock_guard<std::mutex> lock(g_mutex);
        fn = g_transport;
    }
    if (!fn) throw Error("no HTTP transport registered (call novel_core_set_http_transport)");
    return fn(url, headers, timeout);
}

bool looks_like_age_gate(const std::string& body) {
    return contains_ci(body, "18\xe6\xad\xb3\xe4\xbb\xa5\xe4\xb8\x8a\xe3\x81\xa7\xe3\x81\x99\xe3\x81\x8b") ||   // 18歳以上ですか
           contains_ci(body, "\xe5\xb9\xb4\xe9\xbd\xa2\xe7\xa2\xba\xe8\xaa\x8d") ||                                 // 年齢確認
           contains_ci(body, "\xe9\x96\xb2\xe8\xa6\xa7\xe7\xa2\xba\xe8\xaa\x8d") ||                                 // 閲覧確認
           contains_ci(body, "R18\xe9\x96\xb2\xe8\xa6\xa7\xe7\xa2\xba\xe8\xaa\x8d");                               // R18閲覧確認
}

// ゲートページ内の承認リンク(「はい」/Yes 等)を抽出する。
std::optional<std::string> age_gate_link(const std::string& body,
                                         const std::string& custom_regex) {
    std::string pat = custom_regex.empty()
                          ? "href=\"([^\"]+)\"[^>]*>[^<]*(?:\xe3\x81\xaf\xe3\x81\x84|Yes|Enter|18)"  // はい|Yes|Enter|18
                          : custom_regex;
    try {
        Regex re(pat, true, true);  // dotall + icase
        auto m = re.search(body);
        if (!m) return std::nullopt;
        auto g = m->get(1);
        if (!g || g->empty()) return std::nullopt;
        return *g;
    } catch (...) {
        return std::nullopt;
    }
}

std::string cookie_header_from_set_cookies(const std::string& existing,
                                           const std::string& set_cookies) {
    std::string out = existing;
    size_t pos = 0;
    while (pos < set_cookies.size()) {
        size_t nl = set_cookies.find('\n', pos);
        std::string line = set_cookies.substr(pos, nl == std::string::npos ? std::string::npos : nl - pos);
        pos = nl == std::string::npos ? set_cookies.size() : nl + 1;
        size_t eq = line.find('=');
        size_t semi = line.find(';');
        if (eq == std::string::npos) continue;
        std::string nv = trim(line.substr(0, semi == std::string::npos ? line.size() : semi));
        if (nv.empty()) continue;
        if (!out.empty()) out += "; ";
        out += nv;
    }
    return out;
}

std::string decode_body(std::string body, const std::string& /*content_type*/) {
    // Encoding: presets declare UTF-8 for all supported sites; Shift_JIS sites
    // can convert through their own preset-level hooks.  Keep as-is here.
    return body;
}

enum class FetchErrorKind { NotFound, Challenge, RateLimited, Suspend, Other };

struct FetchError : Error {
    FetchErrorKind kind;
    FetchError(FetchErrorKind k, const std::string& msg) : Error(msg), kind(k) {}
};

FetchErrorKind classify_status(int status, const std::string& body) {
    if (status == 404) return FetchErrorKind::NotFound;
    if (status == 429) return FetchErrorKind::RateLimited;
    if (status == 503) return FetchErrorKind::Suspend;
    if (status == 403) {
        if (challenge_sample(body, true)) return FetchErrorKind::Challenge;
        return FetchErrorKind::Other;
    }
    return FetchErrorKind::Other;
}

} // namespace

void set_transport(TransportFn fn) {
    std::lock_guard<std::mutex> lock(g_mutex);
    g_transport = std::move(fn);
}

bool has_transport() {
    std::lock_guard<std::mutex> lock(g_mutex);
    return (bool)g_transport;
}

std::string profile_user_agent(const std::string& profile) {
    if (profile == "safari_mobile" || profile == "safari_ios26_2")
        return "Mozilla/5.0 (iPhone; CPU iPhone OS 26_0 like Mac OS X) AppleWebKit/605.1.15 "
               "(KHTML, like Gecko) Version/26.0 Mobile/15E148 Safari/604.1";
    if (profile == "safari_desktop" || profile == "safari26_2")
        return "Mozilla/5.0 (Macintosh; Intel Mac OS X 26_0) AppleWebKit/605.1.15 "
               "(KHTML, like Gecko) Version/26.0 Safari/605.1.15";
    return "Mozilla/5.0 (Macintosh; Intel Mac OS X 15_0) AppleWebKit/537.36 "
           "(KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36";
}

void HttpClient::set_extra_cookie(const std::string& domain, const std::string& cookie) {
    std::lock_guard<std::mutex> lock(g_mutex);
    std::string d = lower(trim(domain));
    while (!d.empty() && d.front() == '.') d.erase(d.begin());
    g_extra_cookies[d] = cookie;
}

void HttpClient::set_browser_fetch_command(const std::string& command) {
    std::lock_guard<std::mutex> lock(g_mutex);
    g_browser_command = trim(command);
}

void HttpClient::clear_caches() {
    std::lock_guard<std::mutex> lock(g_mutex);
    g_host_retry_after.clear();
}

namespace {
std::optional<std::string> browser_command() {
    std::lock_guard<std::mutex> lock(g_mutex);
    return g_browser_command.empty() ? std::nullopt
                                     : std::optional<std::string>(g_browser_command);
}

std::optional<std::string> host_retry_window(const std::string& host) {
    std::lock_guard<std::mutex> lock(g_mutex);
    auto it = g_host_retry_after.find(host);
    if (it == g_host_retry_after.end()) return std::nullopt;
    auto now = std::chrono::steady_clock::now();
    if (it->second > now) {
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(it->second - now);
        return std::to_string(ms.count());
    }
    g_host_retry_after.erase(it);
    return std::nullopt;
}

void remember_host_retry(const std::string& host, int delay_ms) {
    std::lock_guard<std::mutex> lock(g_mutex);
    g_host_retry_after[host] = std::chrono::steady_clock::now() +
                               std::chrono::milliseconds(delay_ms);
}

int retry_delay_ms(int base_ms, int attempt, bool rate_limited) {
    int exponent = std::min(std::max(attempt - 1, 0), 5);
    int floor_ms = rate_limited ? std::max(base_ms, 10000) : base_ms;
    int delay = floor_ms * (1 << exponent);
    delay += (int)(std::chrono::steady_clock::now().time_since_epoch().count() % 750);
    return std::min(delay, 60000);
}
} // namespace

std::string HttpClient::fetch(const std::string& url,
                              const std::optional<AccessSettings>& access,
                              const std::optional<std::string>& referer_url) {
    std::string host = url_host(url);
    if (host.empty()) throw Error("URL has no host: " + url);
    std::string profile =
        access && access->profile ? *access->profile : "chrome_desktop";

    // challenge fallback profiles: mobile <-> desktop swap
    std::vector<std::string> profiles{profile};
    if (profile == "safari_mobile") profiles.push_back("chrome_desktop");
    else if (profile == "chrome_desktop") profiles.push_back("safari_desktop");
    else profiles.push_back("safari_mobile");

    int retries = 3;
    int attempt = 0;
    while (true) {
        if (auto wait_ms = host_retry_window(host)) {
            std::this_thread::sleep_for(std::chrono::milliseconds(std::stoll(*wait_ms)));
        }
        try {
            // primary attempt
            std::string body;
            bool challenged = false;
            bool age_gate_attempted = false;
            try {
                HttpResponse resp =
                    transport_request(url, browser_headers(profiles[0], url, access, referer_url), 30);
                if (resp.status == 429) throw FetchError(FetchErrorKind::RateLimited, "429");
                if (resp.status == 503) throw FetchError(FetchErrorKind::Suspend, "503");
                if (resp.status == 404) throw FetchError(FetchErrorKind::NotFound, "404");
                // 年齢ゲート(「18歳以上ですか？」等)は confirm_over18 有効時に
                // 「はい」リンクを一度だけ自動クリックして通過を試みる。
                if (access && access->confirm_over18 && !age_gate_attempted &&
                    looks_like_age_gate(resp.body)) {
                    age_gate_attempted = true;
                    if (auto gate = age_gate_link(resp.body, access->age_gate_link_regex)) {
                        std::string gate_url = url_absolute(url, *gate);
                        std::string extra;
                        try {
                            HttpResponse g = transport_request(
                                gate_url,
                                browser_headers(profiles[0], gate_url, access, url), 30);
                            extra = cookie_header_from_set_cookies("", g.set_cookies);
                        } catch (...) {
                        }
                        auto hdrs2 = browser_headers(profiles[0], url, access, referer_url);
                        if (!extra.empty()) {
                            bool merged = false;
                            for (auto& kv : hdrs2) {
                                if (lower(kv.first) == "cookie") {
                                    kv.second += "; " + extra;
                                    merged = true;
                                }
                            }
                            if (!merged) hdrs2.emplace_back("Cookie", extra);
                        }
                        HttpResponse resp2 = transport_request(url, hdrs2, 30);
                        if (resp2.status >= 200 && resp2.status < 300 &&
                            !looks_like_age_gate(resp2.body))
                            return decode_body(resp2.body, "");
                    }
                    throw FetchError(FetchErrorKind::Challenge,
                                     "age confirmation gate (click-through failed)");
                }
                if (challenge_sample(resp.body, false))
                    throw FetchError(FetchErrorKind::Challenge, "challenge page");
                if (resp.status >= 200 && resp.status < 300) {
                    return decode_body(resp.body, "");
                }
                if (resp.status == 403) {
                    bool browser_fb = access && access->browser_fallback;
                    if (browser_fb || challenge_sample(resp.body, true))
                        throw FetchError(FetchErrorKind::Challenge, "403 challenge");
                    throw Error("forbidden response status=403");
                }
                throw Error("invalid response status=" + std::to_string(resp.status));
            } catch (const FetchError& e) {
                if (e.kind == FetchErrorKind::NotFound) throw;
                if (e.kind != FetchErrorKind::Challenge) throw;
                challenged = true;
            }
            if (challenged) {
                // secondary profiles
                for (size_t k = 1; k < profiles.size(); ++k) {
                    try {
                        HttpResponse resp = transport_request(
                            url, browser_headers(profiles[k], url, access, referer_url), 30);
                        if (challenge_sample(resp.body, false)) continue;
                        if (resp.status >= 200 && resp.status < 300)
                            return decode_body(resp.body, "");
                        if (resp.status == 403 && challenge_sample(resp.body, true)) continue;
                    } catch (const FetchError&) {
                        continue;
                    } catch (...) {
                        continue;
                    }
                }
                if (access && access->browser_fallback) {
                    if (auto cmd = browser_command()) {
                        return fetch_via_command(*cmd, url);
                    }
                }
                throw FetchError(FetchErrorKind::Challenge,
                                 "javascript challenge (enable browser fetch fallback?)");
            }
        } catch (const FetchError& e) {
            if (e.kind == FetchErrorKind::NotFound || e.kind == FetchErrorKind::Challenge)
                throw;
            bool rate_limited = e.kind == FetchErrorKind::RateLimited;
            if (retries <= 0) throw;
            --retries;
            ++attempt;
            int delay = retry_delay_ms(3000, attempt, rate_limited);
            remember_host_retry(host, delay);
            std::this_thread::sleep_for(std::chrono::milliseconds(delay));
            continue;
        } catch (const Error& e) {
            if (retries <= 0) throw;
            --retries;
            ++attempt;
            int delay = retry_delay_ms(3000, attempt, false);
            remember_host_retry(host, delay);
            std::this_thread::sleep_for(std::chrono::milliseconds(delay));
            continue;
        }
        break;
    }
    throw Error("fetch failed: " + url);
}

} // namespace nc
